# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFirstTest():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_firstTest(self):
    self.driver.get("https://www.globalsqa.com/angularJs-protractor/BankingProject/")
    self.driver.set_window_size(550, 691)
    self.driver.find_element(By.CSS_SELECTOR, ".center:nth-child(1) > .btn").click()
    self.driver.find_element(By.ID, "userSelect").click()
    dropdown = self.driver.find_element(By.ID, "userSelect")
    dropdown.find_element(By.XPATH, "//option[. = 'Ron Weasly']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-binding:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-default").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-control").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-control").send_keys("100")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-default").click()
    self.driver.find_element(By.CSS_SELECTOR, ".logout").click()
  
